"""Canonical signal / risk reason codes persisted on every audit row."""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    OK = "OK"
    NO_TRADE = "NO_TRADE"
    EDGE_TOO_SMALL = "EDGE_TOO_SMALL"
    STALE_DATA = "STALE_DATA"
    RISK_LIMIT = "RISK_LIMIT"
    MARKET_NOT_HOT = "MARKET_NOT_HOT"
    UNKNOWN_RESOLUTION = "UNKNOWN_RESOLUTION"
    UNKNOWN_FEES = "UNKNOWN_FEES"
    NOT_ACCEPTING_ORDERS = "NOT_ACCEPTING_ORDERS"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    SLIPPAGE_TOO_HIGH = "SLIPPAGE_TOO_HIGH"
    KILL_SWITCH = "KILL_SWITCH"
    LIVE_GATES_BLOCKED = "LIVE_GATES_BLOCKED"
    SHADOW_MODE = "SHADOW_MODE"
    CATEGORY_DISABLED = "CATEGORY_DISABLED"
    BELOW_MIN_SIZE = "BELOW_MIN_SIZE"
    INVALID_TICK = "INVALID_TICK"
    IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
    MARTINGALE_BLOCKED = "MARTINGALE_BLOCKED"
    COOLDOWN = "COOLDOWN"
    DATA_AGE = "DATA_AGE"
    LATENCY = "LATENCY"
    NO_BOOK = "NO_BOOK"
    PAPER_ONLY = "PAPER_ONLY"
